version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    labels:
      - "deps"
      - "deps:pub"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "deps(pub)"
    groups:
      patch-updates:
        update-types:
          - patch
      slang:
        patterns:
          - slang
          - slang_flutter
        update-types:
          - major
          - minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
    labels:
      - "deps"
      - "deps:workflow"
    commit-message:
      prefix: "deps(workflow)"
