version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    labels:
      - "deps"
      - "deps:pub"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    commit-message:
      prefix: "deps(pub)"
    groups:
      slang:
        patterns:
          - slang*
        update-types:
          - major
          - minor
      drift:
        patterns:
          - drift*
          - sqlite3*
        update-types:
          - major
          - minor
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
    labels:
      - "deps"
      - "deps:workflow"
    commit-message:
      prefix: "deps(workflow)"
