targets:
  drift:
    auto_apply_builders: false
    builders:
      drift_dev:analyzer:
        enabled: true
        options: &drift_options
          has_separate_analyzer: true # always enable this option when using `not_shared`
          use_data_class_name_for_companions: true
          databases:
            db: lib/database.dart
      drift_dev:not_shared:
        enabled: true
        options: *drift_options
  freezed:
    auto_apply_builders: false
    dependencies:
      - :drift
    builders:
      freezed:
        enabled: true
        options:
          copy_with: false
          map: false
          when: false
  $default:
    dependencies:
      - :freezed
    builders:
      drift_dev:
        enabled: false
      freezed:
        enabled: false
