targets:
  $default:
    builders:
      drift_dev:
        options:
          use_data_class_name_for_companions: true
      freezed:
        options:
          copy_with: false
          map: false
          when: false
