# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require "yaml"

locale_map = {
  "ja" => "ja",
  "en" => "en-US",
}

default_platform(:ios)

platform :ios do
    desc "Import certs and profiles"
    lane :import_certificates do
        install_provisioning_profile(path: "./secrets/Release.mobileprovision")

        $keychain_name = "app-signing"
        $keychain_password = SecureRandom.hex(100)

        create_keychain(
            name: $keychain_name,
            password: $keychain_password,
            default_keychain: true,
            unlock: true,
            timeout: 3600
        )
        import_certificate(
            certificate_path: "./secrets/dist.p12",
            certificate_password: ENV["APPLE_DIST_CERT_PW"],
            keychain_name: $keychain_name,
            keychain_password: $keychain_password
        )
    end

    desc "Upload to App Store or Testflight"
    lane :upload do
        app_store_connect_api_key(
            key_id: ENV["ASC_KEY_ID"],
            issuer_id: ENV["ASC_ISSUER_ID"],
            key_filepath: ENV["ASC_KEY_FILEPATH"],
        )

        app_version = ENV["APP_VERSION"]
        is_test_version = app_version.include?("-")

        if is_test_version
            upload_to_testflight(
              skip_waiting_for_build_processing: true,
              ipa: "../build/ios/ipa/GenshinMaterial.ipa"
            )
        else
            contents = YAML.safe_load(File.read("../../assets/release_notes.yaml"))
            version_entry = contents.find { |e| e["version"] == app_version }
            if version_entry == nil
                raise "No release note for version #{app_version}. Did you add it?"
            end
            version_entry["contents"]["locales"].each do |locale, contents|
                path = "./metadata/#{locale_map[locale]}/release_notes.txt"
                FileUtils.mkdir_p(File.dirname(path))
                File.write(path, contents)
            end
            upload_to_app_store(
              app_version: app_version,
              skip_screenshots: true,
              precheck_include_in_app_purchases: false,
              submit_for_review: true,
              force: true,
              ipa: "../build/ios/ipa/GenshinMaterial.ipa",
            )
        end
    end

    lane :upload_screenshots do
        upload_to_app_store(
            skip_binary_upload: true,
            skip_metadata: true,
            skip_app_version_update: true,
            overwrite_screenshots: true,
        )
    end
end
