// Mocks generated by Mockito 5.4.6 from annotations
// in genshin_material/test/utils/banner_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:firebase_remote_config/firebase_remote_config.dart' as _i6;
import 'package:genshin_material/data/repositories/remote_config_repository.dart'
    as _i3;
import 'package:genshin_material/models/remote_config_key.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamSubscription_0<T> extends _i1.SmartFake
    implements _i2.StreamSubscription<T> {
  _FakeStreamSubscription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigRepository extends _i1.Mock
    implements _i3.RemoteConfigRepository {
  MockRemoteConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T get<T extends Object>(_i4.RemoteConfigKey<T>? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i5.dummyValue<T>(
              this,
              Invocation.method(#get, [key]),
            ),
          )
          as T);

  @override
  _i2.StreamSubscription<_i6.RemoteConfigUpdate> listenConfigUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#listenConfigUpdate, []),
            returnValue: _FakeStreamSubscription_0<_i6.RemoteConfigUpdate>(
              this,
              Invocation.method(#listenConfigUpdate, []),
            ),
          )
          as _i2.StreamSubscription<_i6.RemoteConfigUpdate>);

  @override
  _i2.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}
