#!/usr/bin/env bash

set -euo pipefail

# Runs the test suite with coverage, strips generated code from the report and
# prints a summary. Pass --html to additionally render an HTML report into
# coverage/html.
#
# `flutter test --coverage` reports only the libraries the test isolate loaded:
# a lib/ file no test reaches is absent from the report entirely rather than
# counted as zero, so the denominator would otherwise grow every time a file
# gets its first test — and the percentage could fall while coverage improved.
# To keep the number comparable between runs, a throwaway test importing every
# lib/ file is generated below, which pins the denominator to all of lib/.

generate_html=false
for arg in "$@"; do
  case "$arg" in
    --html)
      generate_html=true
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Usage: $0 [--html]" >&2
      exit 1
      ;;
  esac
done

# `--ignore-errors unused` below is an lcov 2.0 error class; 1.x rejects it.
print_lcov_install_hint() {
  echo "lcov 2.0 or newer is required." >&2
  echo "  Debian/Ubuntu: sudo apt-get install lcov  (needs Ubuntu 24.04 or newer;" >&2
  echo "                 22.04 ships lcov 1.16, which is too old)" >&2
  echo "  macOS:         brew install lcov" >&2
}

if ! command -v lcov > /dev/null; then
  echo "lcov is not installed." >&2
  print_lcov_install_hint
  exit 1
fi

lcov_version="$(lcov --version)"
if [[ ! "$lcov_version" =~ ([0-9]+)\.[0-9]+ ]] || [ "${BASH_REMATCH[1]}" -lt 2 ]; then
  echo "Found: $lcov_version" >&2
  print_lcov_install_hint
  exit 1
fi

if [ "$generate_html" = true ] && ! command -v genhtml > /dev/null; then
  echo "genhtml is not installed (it ships with lcov)." >&2
  print_lcov_install_hint
  exit 1
fi

# Pins the coverage denominator to all of lib/ (see the note at the top).
# Generated per run and never committed, so it cannot conflict with other work.
coverage_helper="test/coverage_all_imports_test.dart"
trap 'rm -f "$coverage_helper"' EXIT

{
  echo "// GENERATED by scripts/coverage.sh — do not edit, do not commit."
  echo "// ignore_for_file: unused_import, directives_ordering"
  # Part files cannot be imported, and firebase_options.dart is git-ignored.
  find lib -name "*.dart" \
    ! -name "*.g.dart" \
    ! -name "*.freezed.dart" \
    ! -name "*.drift.dart" \
    ! -name "*.steps.dart" \
    ! -path "lib/i18n/*" \
    ! -name "firebase_options.dart" \
    | sort \
    | sed -E 's|^lib/(.*)$|import "package:genshin_material/\1";|'
  echo "void main() {}"
} > "$coverage_helper"

fvm flutter test --coverage

# `--ignore-errors unused` keeps the script alive when a pattern matches nothing
# (e.g. no mockito mocks were touched by the executed tests).
lcov --remove coverage/lcov.info \
  "*.g.dart" \
  "*.freezed.dart" \
  "*.drift.dart" \
  "*.steps.dart" \
  "*.mocks.dart" \
  "lib/i18n/*" \
  "lib/firebase_options.dart" \
  "lib/routes.dart" \
  --ignore-errors unused \
  -o coverage/lcov-filtered.info

lcov --summary coverage/lcov-filtered.info

if [ "$generate_html" = true ]; then
  genhtml coverage/lcov-filtered.info -o coverage/html
  echo "HTML report: coverage/html/index.html"
fi
