#!/usr/bin/env bash

set -euo pipefail

# Runs the test suite with coverage, strips generated code from the report and
# prints a summary. Pass --html to additionally render an HTML report into
# coverage/html.
#
# `flutter test --coverage` reports only the libraries the test isolate loaded:
# a lib/ file no test reaches is absent from the report entirely rather than
# counted as zero, so the denominator would otherwise grow every time a file
# gets its first test — and the percentage could fall while coverage improved.
# To keep the number comparable between runs, a throwaway test importing every
# lib/ file is generated below, which pins the denominator to all of lib/.

generate_html=false
report_only=false
for arg in "$@"; do
  case "$arg" in
    --html)
      generate_html=true
      ;;
    --report-only)
      # Re-print the report from an existing coverage/lcov.info without
      # re-running the tests. Used by CI to fill the job summary.
      report_only=true
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Usage: $0 [--html] [--report-only]" >&2
      exit 1
      ;;
  esac
done

# `--ignore-errors unused` below is an lcov 2.0 error class; 1.x rejects it.
print_lcov_install_hint() {
  echo "lcov 2.0 or newer is required." >&2
  echo "  Debian/Ubuntu: sudo apt-get install lcov  (needs Ubuntu 24.04 or newer;" >&2
  echo "                 22.04 ships lcov 1.16, which is too old)" >&2
  echo "  macOS:         brew install lcov" >&2
}

if ! command -v lcov > /dev/null; then
  echo "lcov is not installed." >&2
  print_lcov_install_hint
  exit 1
fi

lcov_version="$(lcov --version)"
if [[ ! "$lcov_version" =~ ([0-9]+)\.[0-9]+ ]] || [ "${BASH_REMATCH[1]}" -lt 2 ]; then
  echo "Found: $lcov_version" >&2
  print_lcov_install_hint
  exit 1
fi

# Flutter reports line coverage only — its tracefiles carry no function or
# branch records at all — but lcov enables both by default and newer versions
# then fail with "(empty) function coverage enabled but no corresponding
# coverpoints found". Turning them off drops the meaningless FNF:0/FNH:0
# records; the line data is unchanged. `empty` is ignored as well, in case a
# future version raises it for some other absent metric.
lcov_opts=(--rc function_coverage=0 --rc branch_coverage=0)

if [ "$generate_html" = true ] && ! command -v genhtml > /dev/null; then
  echo "genhtml is not installed (it ships with lcov)." >&2
  print_lcov_install_hint
  exit 1
fi

test_status=0

if [ "$report_only" = false ]; then
  # Pins the coverage denominator to all of lib/ (see the note at the top).
  # Generated per run and never committed, so it cannot conflict with other work.
  coverage_helper="test/coverage_all_imports_test.dart"
  trap 'rm -f "$coverage_helper"' EXIT

  {
    echo "// GENERATED by scripts/coverage.sh — do not edit, do not commit."
    echo "// ignore_for_file: unused_import, directives_ordering"
    # Part files cannot be imported, and firebase_options.dart is git-ignored.
    find lib -name "*.dart" \
      ! -name "*.g.dart" \
      ! -name "*.freezed.dart" \
      ! -name "*.drift.dart" \
      ! -name "*.steps.dart" \
      ! -path "lib/i18n/*" \
      ! -name "firebase_options.dart" \
      | sort \
      | sed -E 's|^lib/(.*)$|import "package:genshin_material/\1";|'
    echo "void main() {}"
  } > "$coverage_helper"

  # Both are removed first so that a leftover report from an earlier run can
  # never be mistaken for this one's — CI guards the summary step on
  # lcov-filtered.info, so leaving that behind would defeat the check. Failing
  # tests still produce coverage, and seeing it is most useful exactly then, so
  # hold the status and exit with it later.
  rm -f coverage/lcov.info coverage/lcov-filtered.info
  fvm flutter test --coverage || test_status=$?
fi

if [ ! -f coverage/lcov.info ]; then
  echo "coverage/lcov.info was not generated; skipping the report." >&2
  # Always non-zero: a missing tracefile is a failure in its own right, whether
  # or not the tests passed.
  exit "$(( test_status != 0 ? test_status : 1 ))"
fi

# `--ignore-errors unused` keeps the script alive when a pattern matches nothing
# (e.g. no mockito mocks were touched by the executed tests).
# -q drops the progress chatter and lcov's own trailing summary, which would
# otherwise be duplicated into the CI job summary. Warnings and errors remain.
lcov -q "${lcov_opts[@]}" --remove coverage/lcov.info \
  "*.g.dart" \
  "*.freezed.dart" \
  "*.drift.dart" \
  "*.steps.dart" \
  "*.mocks.dart" \
  "lib/i18n/*" \
  "lib/firebase_options.dart" \
  "lib/routes.dart" \
  --ignore-errors unused,empty \
  -o coverage/lcov-filtered.info

# `lcov --list` would show this, but lcov 2.0 (checked against 2.0-1) prints
# every rate as 0.0% for these tracefiles — reproduced on a four-line synthetic
# one — so the breakdown is computed here instead. The overall
# percentage alone hides per-directory movement: most of lib/ is UI code that
# this effort deliberately leaves untested, which dominates the total.
echo
echo "Coverage by directory (most uncovered lines first):"
awk -F: '
  /^SF:/ {
    path = $2
    sub(/^.*\/lib\//, "lib/", path)
    idx = 0
    for (i = length(path); i > 0; i--) if (substr(path, i, 1) == "/") { idx = i; break }
    dir = (idx > 0) ? substr(path, 1, idx - 1) : "."
    next
  }
  /^LF:/ { total[dir] += $2 }
  /^LH:/ { hit[dir] += $2 }
  END { for (d in total) printf "%d\t%d\t%d\t%s\n", total[d] - hit[d], hit[d], total[d], d }
' coverage/lcov-filtered.info \
  | sort -rn \
  | awk -F'\t' '
      BEGIN { printf "%-46s %7s %7s %7s %7s\n", "Directory", "Hit", "Miss", "Total", "Rate" }
      { printf "%-46s %7d %7d %7d %6.1f%%\n", $4, $2, $1, $3, ($3 ? 100 * $2 / $3 : 0) }'
echo

lcov "${lcov_opts[@]}" --summary coverage/lcov-filtered.info

if [ "$generate_html" = true ]; then
  genhtml "${lcov_opts[@]}" coverage/lcov-filtered.info -o coverage/html
  echo "HTML report: coverage/html/index.html"
fi

exit "$test_status"
