name: Deploy to Stores
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-attr:
    runs-on: ubuntu-latest
    env:
      BUILD_NUM_OFFSET: 22
    outputs:
      build_num: ${{ steps.build-attr.outputs.build_num }}
      build_name: ${{ steps.build-attr.outputs.build_name }}
      asset_channel: ${{ steps.build-attr.outputs.asset_channel }}

    steps:
      - id: build-attr
        run: |
          echo "build_num=$(($GITHUB_RUN_NUMBER + $BUILD_NUM_OFFSET))" >> $GITHUB_OUTPUT
          echo "build_name=`echo "$GITHUB_REF_NAME" | perl -nle "print $& while m/(?<=v)\d+\.\d+\.\d+/g"`" >> $GITHUB_OUTPUT
          echo "asset_channel=$([[ "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "prod" || echo "dev")" >> $GITHUB_OUTPUT

  deploy-app-store:
    name: Deploy to App Store
    needs: build-attr
    uses: chika3742/flutter-app-deploy/.github/workflows/ios.yml@main
    with:
      build-name: ${{ needs.build-attr.outputs.build_name }}
      build-number: ${{ needs.build-attr.outputs.build_num }}
      build-options: "--dart-define=ASSET_CHANNEL=${{ needs.build-attr.outputs.asset_channel }}"
    secrets:
      provisioning_profile_1_base64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
      codesign_cert_base64: ${{ secrets.APPLE_DIST_CERT_BASE64 }}
      codesign_cert_pw: ${{ secrets.APPLE_DIST_CERT_PW }}
      google_service_info_plist_base64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
      asc_key_id: ${{ secrets.ASC_KEY_ID }}
      asc_issuer_id: ${{ secrets.ASC_ISSUER_ID }}
      asc_key_base64: ${{ secrets.ASC_AUTH_KEY_BASE64 }}

  deploy-play-store2:
    name: Deploy to Play Store
    needs: build-attr
    uses: chika3742/flutter-app-deploy/.github/workflows/android.yml@main
    with:
      build-name: ${{ needs.build-attr.outputs.build_name }}
      build-number: ${{ needs.build-attr.outputs.build_num }}
      build-options: "--dart-define=ASSET_CHANNEL=${{ needs.build-attr.outputs.asset_channel }}"
      wif-provider: ${{ vars.WIF_PROVIDER }}
      wif-service-account: ${{ vars.WIF_SERVICE_ACCOUNT }}
      wif-audience: ${{ vars.WIF_AUDIENCE }}
    secrets:
      keystore_base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      key_properties_base64: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}
      google_services_json_base64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}

concurrency:
  group: deploy
  cancel-in-progress: true
