name: Renovate

on:
  schedule:
    - cron: "17 * * * *"
      timezone: "Asia/Tokyo"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: renovate

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ vars.RENOVATE_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Run Renovate
        uses: renovatebot/github-action@v46.3.7
        with:
          token: ${{ steps.app-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
